import Login from "@/components/auth/Login";
import "../globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <Link href="/" className="m-4 absolute z-50 btn btn-base-300">
          Home
        </Link>
        {children}
      </body>
    </html>
  );
}
